# Generated by Django 4.2.7 on 2023-11-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumparator',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cumparator',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
