# Generated by Django 4.2.7 on 2024-01-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_equipment_feedback_order_stadium_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='temporary', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='temporary', max_length=150),
        ),
    ]
