# Generated by Django 4.2.7 on 2024-01-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_alter_feedback_user_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stadium',
            name='image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
