# Generated by Django 4.2.7 on 2024-01-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_equipment_image_url_stadium_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='image_url',
        ),
    ]
